{
 "title": "Churn Model Monitoring",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Champion Model Historic Metrics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT insert_datetime, f1_score, roc_auc, log_loss from models where model_version = (select max(model_version) from models);"
    }
   ]
  },
  {
   "title": "Champion Model Current Metrics",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT * from models where model_version = (select max(model_version) from models);"
    }
   ]
  },
  {
   "title": "Model Accuracy Comparison",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT model_version, metrics_type, avg(accuracy) from models\ngroup by model_version, metrics_type;"
    }
   ]
  }
 ]
}