name: Push to GCP VM
on:
  push:
    branches:
      - main
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "./"
          TARGET: "/home/admin/churn-pipeline"
