name: Push to GCP VM
on:
  push:
    branches:
      - main
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/admin/churn-pipeline
            git pull https://github.com/raashidsalih/churn-pipeline.git
